### ISSUE TITLE
Any error output from cli_install.php is supressed by default making debugging problems very hard

### ISSUE THREAD

**Issue by cbxp** [bitnami/bitnami-docker-opencart#101]
**Description**

`debug_execute` is used to run `cli_install.php`, which suppressed all error output by default.
Either `debug_execute` should be removed or it should be documented that `BITNAMI_DEBUG=true` must be set to see any installation errors.

**Steps to reproduce the issue:**

1. Run the image with some wrong env vars

**Describe the results you received:**

It just stops without any error output or logs

**Describe the results you expected:**

Any errors should be visible in the logs after container has crashed.

**Additional information you deem important (e.g. issue happens only occasionally):**

I am still trying to figure out how to run the image in Google Cloud Kubernetes through cloud-sql-proxy.

**Comment by cbxp** [comment]
Update: the error that I am getting in Kubernetes (after setting `BITNAMI_DEBUG=true`):

```
PHP Fatal error:  Uncaught Error: Class 'Opencart\System\Engine\Registry' not found in /opt/bitnami/opencart/install/cli_install.php:60
Stack trace:
#0 {main}
  thrown in /opt/bitnami/opencart/install/cli_install.php on line 60
```

**Comment by javsalgar** [comment]
Hi, thank you for the feedback! I agree that we should make a bit more explicit in our container documentation that BITNAMI_DEBUG=true is necessary for checking installation errors. As a user, do you think that a note/section in the README.md file would be enough?
