### ISSUE TITLE
OpenCart index page look like confused

### ISSUE THREAD

**Issue by chendelin1982** [bitnami/bitnami-docker-opencart#102]
**Description**

I am not modify docker-compose.yml, just git clone repo and docker-compose up it.  All container is running OK, but the OpenCart index page look like below

![image](https://user-images.githubusercontent.com/16741975/129709324-8975d6dc-13a6-41b6-b206-dd3ae4402df3.png)

**Comment by juan131** [comment]
Hi @chendelin1982 

As it's mentioned in the section below of the README.md:

- https://github.com/bitnami/bitnami-docker-opencart#how-to-use-this-image

> Note: If you want to access your application from a public IP or hostname you need to configure OpenCart for it. You can handle it adjusting the configuration of the instance by setting the environment variable OPENCART_HOST to your public IP or hostname.

Did you configure the `OPENCART_HOST` accordingly to the IP/hostname you're using to access your Opencart installatin?
