### ISSUE TITLE
Installing Extension via FTP 

### ISSUE THREAD

**Issue by sajayi** [bitnami/bitnami-docker-opencart#24]
I've mounted the opencart_data folder on my local filesystem but when I attempt to install a payment extension via FTP it doesn't appear under Payment Extensions. How can I solve this please?

**Comment by juan131** [comment]
@sajayi the Bitnami OpenCart Docker Images doesn't include a FTP server on it. Did you install it? Could you give more details about the steps you followed in order to install the extension and what extension you installed?

**Comment by sajayi** [comment]
I had to revert to a regular installation of opencart in order to test. Thanks.
