### ISSUE TITLE
EEXIST: Files exists error.

### ISSUE THREAD

**Issue by javierpra** [bitnami/bitnami-docker-opencart#37]
Hello,

I'm receiving the error below when running the latest version of opencart on Centos 7.  Any advise would be appreciated.  Also find the requested information after the error message.

sudo docker-compose up
Creating javpra_mariadb_1
Creating javpra_opencart_1
Attaching to javpra_mariadb_1, javpra_opencart_1
mariadb_1   | nami    INFO  Initializing mariadb
mariadb_1   | Error executing 'postInstallation': 2017-02-19  1:12:36 140162123032448 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 55 ...
mariadb_1   | 
javpra_mariadb_1 exited with code 1
opencart_1  | nami    INFO  Initializing apache
opencart_1  | apache  INFO  ==> Patching httpoxy...
opencart_1  | Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
javpra_opencart_1 exited with code 1

sudo docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

cat docker.info 
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.4 MiB
Name: MyHostname
ID: DAJU:WOWB:YAK2:GBHP:5V3U:UYB5:4NGB:NIAV:DCWR:CJAO:F5UV:Y4VQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by sameersbn** [comment]
@javierpra I believe this is a because your docker host is using overlayfs as the storage backend for docker. We have seen similar issues with Redhat/CentOS hosts before and we recommend switching to a more stable storage driver. See https://github.com/bitnami/bitnami-docker-testlink/issues/17#issuecomment-261783035 for a sample test command.

Do let us the results..

**Comment by javierpra** [comment]
@sameersbn  I switched to the devicemapper storage backend and it seems to work.  Thanks.

**Comment by sameersbn** [comment]
Thanks for confirming this :+1:

**Comment by sameersbn** [comment]
**Update:**

RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2. 

We hope you find the information contained in this referenced document useful.

**Comment by javierpra** [comment]
Hello @Sameer Naik,  sorry for the delay in response.  This does in fact
seem to be the issue.  Once I switched drivers the errors went away.  Thank
you for the quick response.
