### ISSUE TITLE
Opencart 3.0

### ISSUE THREAD

**Issue by fsc7** [bitnami/bitnami-docker-opencart#48]
What should I change to get Opencart 3.0 instead of version 2.3.0.2 ?
Is it possible using your container image?

**Comment by carrodher** [comment]
Hi,

We are working on the Opencart 3.0.0.0 release. In the coming days, it will be available.
I'll come back here to notify you and close the issue when it's ready.

**Comment by fsc7** [comment]
Thanks! I am looking forward to it.

**Comment by carrodher** [comment]
Hi @fsc7,

**Opencart 3.0.0.0 is now available.**
I will close this issue, if you have any other questions or issues with the new Opencart, please do not hesitate to let us know opening a new issue.

Regards
