### ISSUE TITLE
Docker secrets

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [bitnami/bitnami-docker-opencart#54]
It would be great if the image can support docker secrets to bind db passwords.

**Comment by juan131** [comment]
We're not supporting that functionality at this very moment. You can use "Secrets" with this Docker Image using Kubernetes. 

As you can check on the Helm Chart designed for this solution: https://github.com/kubernetes/charts/tree/master/stable/opencart

Secrets can be set using Bitnami Opencart on K8s. See [secrets.yaml](https://github.com/kubernetes/charts/blob/master/stable/opencart/templates/secrets.yaml) and [deployment.yaml](https://github.com/kubernetes/charts/blob/master/stable/opencart/templates/deployment.yaml)
