### ISSUE TITLE
HTTPS url is HTTP

### ISSUE THREAD

**Issue by zhovner** [bitnami/bitnami-docker-opencart#55]
By default `define('HTTPS_SERVER', '')`  var is defined as `htttp` url in configs:

```
/bitnami/opencart/admin/config.php
/bitnami/opencart/config.php
```
This brakes HTTPS support.
It's impossible to change HTTPS base url from admin panel and requires to edit config files manually.

The right way should be: 

```
// HTTP
define('HTTP_SERVER', 'http://my-shop.com/admin/');
define('HTTP_CATALOG', 'http://my-shop.com/');
// HTTPS
define('HTTPS_SERVER', 'https://my-shop.com/admin/');
define('HTTPS_CATALOG', 'https://my-shop.com/');
```

**Comment by tompizmor** [comment]
hi @zhovner,

Thanks for reporting this issue. I was able to reproduce it. 
We will work on fixing it and it will be included in the future versions. We will update this issue once we relase a version containing the fix.

**Comment by zhukovra** [comment]
Quick fix:
`sed -i '5,7s/http:/https:/' /bitnami/opencart/config.php /bitnami/opencart/admin/config.php`

**Comment by tompizmor** [comment]
Hello @zhovner @zhukovra !!

I just wanted to let you know that we have just fixed the issue in the latest image release. 
Please re-open the issue if you find that is not working fine for you.

**Comment by ergbouncex** [comment]
I am seeing this issue again with the latest image [eea095b40e27](url)

**Comment by juan131** [comment]
Hi @zhukovra 

This image was very recently changed, and the configuration is now based on Bash scripts. Find more information at:

- https://github.com/bitnami/bitnami-docker-opencart#303-6-debian-10-r65

The script below fixes the issue:

- https://github.com/bitnami/bitnami-docker-opencart/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/opencart/updatehost.sh

However, it seems it's not being executed during the initialisation. 

I created a PR to fix it.

**Comment by ergbouncex** [comment]
@juan131 Fernando Gomez says hello 👋 😆

**Comment by juan131** [comment]
Still waiting for someone from the team to review the PR..

> @juan131 Fernando Gomez says hello 👋 😆

Give him a hug @ergbouncex !! (and also tell him I'd have expected him to do the PR, he knows better than me about this kind of stuff 😂  )
