### ISSUE TITLE
Extension install issue - Signature hash does not match

### ISSUE THREAD

**Issue by sahas-** [bitnami/bitnami-docker-opencart#57]
**Description**
I'm attempting to install extension and getting this error " Signature hash does not match!"

**Steps to reproduce the issue:**

1. Goto admin site
2. Extensions -->Marketplace --> install 

**Describe the results you received:**
Error:  Signature hash does not match!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
I'm running bitnami/opencart:3.0.2-0-r21

- Output of `docker version`:

```
Docker version 18.06.0-ce, build 0ffa825
```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TEFB:JKPO:2EDR:I54S:EI66:3BLG:DUKR:HJ6I:M3K4:S2ZA:I46O:VUSW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 78
 System Time: 2018-08-05T02:57:22.475758Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @sahas-, we were able to reproduce this issue if the domain and API key weren't properly configured.

Could you check if your domain matches the one you configured in the "Your Stores" section at [opencart.com](https://www.opencart.com)?
If it is wrong and you need to change the host, you must do one of the following:

- Delete the Docker volume and relaunch the container with the `OPENCART_HOST` environment variable.
- Inside the currently running OpenCart container, change the current hostname in the following files:

        /opt/bitnami/opencart/config.php
        /opt/bitnami/opencart/admin/config.php

    You might also need to restart the Docker container for changes to take effect.

Note that, apart from ensuring the hostname matches the one on opencart.com, you also need to enter the Marketplace API Key (top right blue box in the Marketplace).

Hope it helps!

**Comment by alexlii1971** [comment]
Hello,

I tried the version opencart2.2.0.0, opencart2.3.0.2,opencart3.0.3.2,opencart3.0.3.6, and the issue reproduced on all of these version.

I can generate API Secret, and already tried hundreds of time, but still not found a way to resolve it.

Any suggestion please?

Thanks

**Comment by rafariossaa** [comment]
Hi,
  Those files should be inside the container, not in your server.
  Could you check that ?

**Comment by alexlii1971** [comment]
> Hi,
> Those files should be inside the container, not in your server.
> Could you check that ?

> Hi,
> Those files should be inside the container, not in your server.
> Could you check that ?

Hello@bitnami

 Thanks for reply.

Sorry, I do not understand what you mean by container here, and I search on google for opencart container, but I did not found useful ino.

Would you please clarify what or where is the directory? do you mean local opencart files download from Github? or some directory on Linux please?

Thanks in advance.

**Comment by rafariossaa** [comment]
Hi,
  If you are running opencart in docker, most probably you have done what is indicated in the `README.md`
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-opencart/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```
 So, if you run `docker ps` you should see your containers running, something similar to this:
```
$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                         NAMES
f5a82f238bb8        bitnami/opencart:3-debian-10     "/opt/bitnami/script…"   3 minutes ago       Up 3 minutes        0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitnami-docker-opencart_opencart_1
80c98678d04b        bitnami/mariadb:10.3-debian-10   "/opt/bitnami/script…"   3 minutes ago       Up 3 minutes        3306/tcp                                      bitnami-docker-opencart_mariadb_1
```
Now you can get into the running opencart container, and check the existing files :
```
$ docker exec -it bitnami-docker-opencart_opencart_1 bash

I have no name!@f5a82f238bb8:/$ ls -l /opt/bitnami/opencart/
total 64
drwxrwxr-x 1 daemon root  4096 Oct 15 08:15 admin
drwxrwxr-x 1 daemon root  4096 Oct  8 15:11 catalog
-rw-rw-r-- 1 daemon root     0 Oct  8 15:07 config-dist.php
lrwxrwxrwx 1   1001 root    28 Oct 15 08:15 config.php -> /bitnami/opencart/config.php
drwxrwxr-x 1 daemon root  4096 Oct  8 15:11 image
-rw-rw-r-- 1 daemon root   293 Oct  8 15:07 index.php
-rw-rw-r-- 1 daemon root 34529 Oct  8 15:07 license.txt
drwxrwxr-x 1 daemon root  4096 Oct  8 15:11 licenses
-rw-rw-r-- 1 daemon root   418 Oct  8 15:07 php.ini
drwxrwxr-x 1 daemon root  4096 Oct 15 08:15 system
I have no name!@f5a82f238bb8:/$ 
```
About the token issue, let's see what they answer your in that thread.

**Comment by marcosbc** [comment]
For the token issue, make sure you register your site at OpenCart.com (meaning your site would need to be publicly accessible):

![Screen Shot 2020-11-03 at 16 08 48](https://user-images.githubusercontent.com/5102866/98004189-e9183880-1def-11eb-8429-01db4df6d7be.png)

And then enter the API information in your OpenCart site:

![Screen Shot 2020-11-03 at 16 07 12](https://user-images.githubusercontent.com/5102866/98004233-f7665480-1def-11eb-8b5b-6095ac2d9528.png)

After that it should work.
