### ISSUE TITLE
opencart_1  | Error executing 'postInstallation': Server returned status code 404 from http://127.0.0.1/install/index.php?route=upgrade/upgrade

### ISSUE THREAD

**Issue by sawrus** [bitnami/bitnami-docker-opencart#59]
**Description**
After stopping the container and starting up again I get the following error:
opencart_1  |
opencart_1  | Welcome to the Bitnami opencart container
opencart_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
opencart_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
opencart_1  |
opencart_1  | nami    INFO  Initializing apache
opencart_1  | apache  INFO  ==> Patching httpoxy...
opencart_1  | apache  INFO  ==> Configuring dummy certificates...
opencart_1  | nami    INFO  apache successfully initialized
opencart_1  | nami    INFO  Initializing php
opencart_1  | nami    INFO  php successfully initialized
opencart_1  | nami    INFO  Initializing mysql-client
opencart_1  | nami    INFO  mysql-client successfully initialized
opencart_1  | nami    INFO  Initializing libphp
opencart_1  | nami    INFO  libphp successfully initialized
opencart_1  | nami    INFO  Initializing opencart
opencart_1  | opencar INFO  Upgrading OpenCart...
opencart_1  | Error executing 'postInstallation': Server returned status code 404 from http://127.0.0.1/install/index.php?route=upgrade/upgrade
opencart_1  | Server returned status code 404 from http://127.0.0.1/install/index.php?route=upgrade/upgrade

**Steps to reproduce the issue:**
docker-compose up --no-recreate opencart

**Comment by juan131** [comment]
Hi @sawrus 

I was unable to reproduce it. As you can check, Opencart was able to initialise after restarting:

```
...
opencart_1  | nami    INFO  Initializing opencart
opencart_1  | opencar INFO  Upgrading OpenCart...
opencart_1  | opencar INFO  Upgrade finished
opencart_1  | opencar INFO  Configuring permissions
opencart_1  | opencar INFO
opencart_1  | opencar INFO  ########################################################################
opencart_1  | opencar INFO   Installation parameters for opencart:
opencart_1  | opencar INFO     Persisted data and properties have been restored.
opencart_1  | opencar INFO     Any input specified will not take effect.
opencart_1  | opencar INFO   This installation requires no credentials.
opencart_1  | opencar INFO  ########################################################################
opencart_1  | opencar INFO
opencart_1  | nami    INFO  opencart successfully initialized
...
```

- What version of Opencart are you using?
- What version of Docker are you using?
- Did you try to restart again the container?
