### ISSUE TITLE
rebuilding to work with mysql instead of mariadb

### ISSUE THREAD

**Issue by ifridemberg** [bitnami/bitnami-docker-opencart#63]
Hi, 
I have a little few changes to the images  and a docker-compose file, but when to execute the docker-compose, I get the following messages:
opencart    | Error executing 'postInstallation': Failed to connect to 127.0.0.1:3306 after 36 tries
opencart    | nami    INFO  Initializing opencart
opencart    | mysql-c INFO  Trying to connect to MySQL server

However, the above messages when I attempt to connect manually from opencart container to mysql container, it works fine. 
I attach the Dockerfile and docker-compose. 
I'll thank any help.

best regards

[bitnamiOpencartMysql.txt](https://github.com/bitnami/bitnami-docker-opencart/files/2751664/bitnamiOpencartMysql.txt)
[Dockerfile.txt](https://github.com/bitnami/bitnami-docker-opencart/files/2751665/Dockerfile.txt)

**Comment by andresbono** [comment]
Hi @ifridemberg, this issue seems to be closely related to #62. Let me close this one in favor of the other!
