### ISSUE TITLE
Mount /opt/bitnami/opencart

### ISSUE THREAD

**Issue by dennypenta** [bitnami/bitnami-docker-opencart#65]
We have two directories:
- /opt/bitnami/opencart
- /bitnami/opencart

The real source code that I can use for local development, make any changes that's valuable for me is first one.
You propose mount the second.
Can you explain why and how does it work?
I tried to mount first for local development, but I couldn't run container with an error:
`Error executing 'postInstallation': Program exited with exit code 1`

**Comment by dennypenta** [comment]
Closed, is the same as https://github.com/bitnami/bitnami-docker-opencart/issues/51
I'll make PR for those guys like me who missed this detail.

**Comment by tompizmor** [comment]
Thanks @dennypenta!
