### ISSUE TITLE
wrong requirements for smtp configuration

### ISSUE THREAD

**Issue by xdmitry** [bitnami/bitnami-docker-opencart#69]
**Description**

if you configure smtp host, installer also asks you to configure user, password and port

**Steps to reproduce the issue:**

docker run -e SMTP_HOST=127.0.0.1 -e ALLOW_EMPTY_PASSWORD=yes -e MARIADB_HOST=<host> bitnami/opencart:3

**Describe the results you received:**
...
opencar INFO  Configuring SMTP...
Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration

**Describe the results you expected:**

smtp server configured without username and password with default port 25

**Additional information you deem important (e.g. issue happens only occasionally):**

it is possible to configure just host with opencart in admin section

**Version**

any

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

any

**Comment by alemorcuq** [comment]
Hi, @xdmitry.

Thank you for reporting this. We will evaluate it and come back to you with an answer.

Regards,
Alejandro

**Comment by beltran-rubo** [comment]
Hi @xdmitry, the new released image "3.0.3-2-debian-10-r31" does not require to configure the SMTP user & password. Please give a try and let us know if that fixed your issue.
