### ISSUE TITLE
Artifacts link to 127.0.0.1 after destroying/scaling container

### ISSUE THREAD

**Issue by parksquare** [bitnami/bitnami-docker-opencart#73]
**Issue Description** 

Had a fully working system, with OPENCART_HOST set before creating the container for the first time, as described in other closed issues. 

If the container is destroyed and recreated (with exactly the same parameters) the following happens:

- OPENCART_HOST is ignored and config.php is overwritten with 127.0.0.1 in both config.php and admin/config.php

- Public site starts but js, images, css fail to load because the links are now 127.0.0.1. Site is effectively unusable.

- Admin site is not accessible as the redirect refers to 127.0.0.1, so cannot log in

- While the container is coming back up, the end user sees a Bitnami holding page saying the app is being configured. The end user should never see this once the site has been initially set up. 

**Expected Behaviour**

It should be possible to destroy the container for any reason, and for a new instance to be stood up without any config being corrupted. The Bitnami holding page should not be shown if existing config data is found in /bitnami directory.

**Workaround**

Manually editing the two config.php files does resolve the issue, simply change the references to 127.0.0.1 back to the correct hostname.

This makes the container rather unresilient to any changes, and definitely not suitable for a live environment.

Seems somewhat similar to https://github.com/bitnami/bitnami-docker-opencart/issues/61 but the solution to simply destroy the volumes and recreate isn't viable once a live site is up and running.

**Comment by jotamartos** [comment]
Hi @parksquare,

Thank you for taking the time to report this issue. Some questions before working on reproducing the issue. 

- Did you set any other variable when starting the container?

https://github.com/bitnami/bitnami-docker-opencart#environment-variables

> If the container is destroyed and recreated (with exactly the same parameters) the following happens:

- Did you use "docker-compose down" to destroy the container or did you use any other method? I understand you didn't remove the volumes when destroying the container, right?

Thanks

**Comment by parksquare** [comment]
It's deployed using Rancher. Here are the variables set on the OpenCart container with some parts redacted:

![image](https://user-images.githubusercontent.com/14939654/68135188-2e730300-ff1b-11e9-8e7b-124d3838baaa.png)

The volumes are not removed when destroying the container. 

All data seems to be persisted okay, with the exception of the host name that reverts to 127.0.0.1. Changing those in the web and admin config files back to www.myhostname.co.uk fixed the site, and everything works normally again.

**Comment by jotamartos** [comment]
Hi @parksquare,

We tried to reproduce the issue using the docker-compose.yml file but couldn't do so. The application was configured correctly after recreating it (docker-compose down and docker-compose up). We checked both config.php and admin/config.php (the code below belongs to this file) and they both included the example domain I used. We also accessed the application's page and its admin dashboard and there was not any reference to 127.0.0.1

```
<?php
// HTTP
define('HTTP_SERVER', 'http://jota.com/admin/');
define('HTTP_CATALOG', 'http://jota.com/');
// HTTPS
define('HTTPS_SERVER', 'https://jota.com/admin/');
define('HTTPS_CATALOG', 'https://jota.com/');
...
```

Could you please add the following environment variable to your deployment (NAMI_LOG_LEVEL=trace8), recreate the container and share all the log information with us? We would like to investigate this issue further to avoid issues in the future.

Thanks.

**Comment by parksquare** [comment]
I set the trace variable and have attached the logs. Tried it a few times, with the same result. It no longer seems to be resetting the config and is working as expected. Nothing else has changed that I know of, so can't really explain why it is okay now. I was using the 'latest' tag, but looking at the output of 'docker image ls' and your version history, seems to suggest the image has not changed since the initial deployment? 

[container.log](https://github.com/bitnami/bitnami-docker-opencart/files/3828422/container.log)

**Comment by parksquare** [comment]
I would say that if you detect existing data/config when the container starts up, it would be better to return a maintenance page that is more in keeping with the site itself rather than your blue Bitnami branded one, which is only really appropriate on first launch. 

Thanks for your efforts guys, keep up the good work.

**Comment by rafariossaa** [comment]
Hi @parksquare,
  I was not able to reproduce the issue. 
  There is a step where HTTP_SERVER is changed by 127.0.0.1 and then replaced by what was set before.
  Could you change that value manually, stop and start it again and paste here the logs of the opencart container ?

**Comment by parksquare** [comment]
To clarify, do you mean set HTTP_SERVER to something else (e.g. www.fakedomain.com) other than the real domain name I'm using?

**Comment by rafariossaa** [comment]
If the issues is that when it is restarted it shouldn't been changing the HTTP_SERVER set by 127.0.0.1, then it really doesn't matter the value you set HTTPS_SEVER.
What I am interested is in the log. There are some messages that could give me a clue of what is happening in your case.
When I tried it, it replaces momentarily the HTTP_SERVER you set by 127.0.0.1 to be able to run the upgrade wizard, and then it replaces it again for the value you have set.
It seems that second step is not taking place for some reason.

**Comment by parksquare** [comment]
I'd like to reopen this. I've moved the container to a different host, which meant getting a newer image than before. However even if I explicitly tell it to use bitnami/opencart:3.0.3-2-r20, it still rewrites the host entries in config to 127.0.0.1. 

The trick of just manually updating the config again doesn't work.

Is there any way to override this behaviour?

```
Welcome to the Bitnami opencart container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami INFO Initializing apache
apache INFO ==> Patching httpoxy...
apache INFO ==> Configuring dummy certificates...
nami INFO apache successfully initialized
nami INFO Initializing php
nami INFO php successfully initialized
nami INFO Initializing mysql-client
nami INFO mysql-client successfully initialized
nami INFO Initializing libphp
nami INFO libphp successfully initialized
nami INFO Initializing opencart
opencar INFO Upgrading OpenCart...
Error executing 'postInstallation': Server returned status code 404 from http://127.0.0.1/install/index.php?route=upgrade/upgrade
Server returned status code 404 from http://127.0.0.1/install/index.php?route=upgrade/upgrade


```

**Comment by parksquare** [comment]
Is there any update on this? The other issue I opened was a slightly different scenario, i.e. OpenCart is trying to upgrade itself rather than the same version simply being a new container using the existing data from a destroyed container. 

Is there any way to override this behaviour, it's really unhelpful doing this with the config especially since 127.0.0.1 isn't necessarily going to work.

**Comment by rafariossaa** [comment]
Hi @parksquare ,
  Let me open an internal task to investigate this.
  We will come back to you when we have news.

**Comment by carrodher** [comment]
This is not `stale`, we have a task in our backlog, as the issue is not critical we are not going to work on it immediately, but it will be taken into account for future releases.

I will add the proper labels to avoid `stale-bot` closing this case.

**Comment by jasonfdriskill** [comment]
Same issue.

```sh

nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing opencart
opencar INFO  Preparing webserver environment...
opencar INFO  Preparing PHP environment...
opencar INFO  Upgrading OpenCart...
Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/install/index.php?route=upgrade/upgrade
Server returned status code 500 from http://127.0.0.1/install/index.php?route=upgrade/upgrade

```

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for the feedback. As @carrodher said this is in our backlog.
