### ISSUE TITLE
Extensions lost after compose restart

### ISSUE THREAD

**Issue by vondraussen** [bitnami/bitnami-docker-opencart#74]
Hi,
I'm using docker-compose to run the containers (opencart and mariadb).
If I install an extension, for example a language pack:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31048
It works well, until I stop the stack and restart it.

The Extension is somehow not usable anymore. The admin portal still mention it as installed but it is not working. If I remove it and install it again, it will work again.

I'm using the example docker-compose file.

**Comment by jotamartos** [comment]
Hi @vondraussen ,

Thank you for reporting this issue. The app's folders are not persisted correctly and that's why the extension doesn't work properly when stopping/starting the container. I installed the extension and the following files were modified 

```
root@79730e7b9c5e:/opt/bitnami/opencart# git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   admin/view/image/payment/secure_trading.png
        modified:   admin/view/image/payment/skrill.png
        modified:   admin/view/javascript/jquery/jqvmap/maps/jquery.vmap.world.js
        modified:   admin/view/javascript/summernote/lang/summernote-de-DE.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        admin/language/de-de/
        admin/view/image/payment/voicepay.png
        admin/view/javascript/jquery/datetimepicker/locale/
        admin/view/javascript/jquery/jqvmap/maps/jquery.vmap.europe_de.js
        catalog/language/de-de/
        catalog/view/javascript/jquery/datetimepicker/locale/

no changes added to commit (use "git add" and/or "git commit -a")
```

The team will take a look at them and modify the container's configuration. We will update this ticket once we have more information.

**Comment by nicexe** [comment]
Persistence is currently set to `/bitnami` yet the files served are in `/opt/bitnami/`.
There are only 2 symlinks in `/opt/bitnami/` to `/bitnami` as seen here:
```
# ls -la /opt/bitnami/opencart/
total 88
drwxr-xr-x 1 root   root    4096 Apr 20 22:18 .
drwxrwxr-x 1 root   root    4096 Apr 20 13:33 ..
-rw-r--r-- 1 root   root       0 Jan 23 18:45 .buildcomplete
-rw-r----- 1 root   root     151 Apr 20 22:17 .htaccess
drwxr-xr-x 1 root   root    4096 Apr 20 22:17 admin
drwxr-xr-x 1 daemon daemon  4096 Apr 20 13:33 catalog
lrwxrwxrwx 1 root   root      28 Apr 20 22:17 config.php -> /bitnami/opencart/config.php
lrwxrwxrwx 1 root   root      23 Apr 20 22:17 image -> /bitnami/opencart/image
-rw-r--r-- 1 root   root     293 Jan 23 18:45 index.php
-rw-r--r-- 1 root   root   34529 Jan 23 18:45 license.txt
drwxr-xr-x 2 root   root    4096 Apr 20 13:33 licenses
drwxr-xr-x 1 root   root    4096 Apr 20 22:17 system
```

**Comment by andresbono** [comment]
Exactly, @nicexe. In order to allow the extensions persist a restart some other directories should be stored in the `/bitnami` path. Unfortunately, we have not addressed this issue yet.

**Comment by cssdata** [comment]
Still the same (July 2020). This is a pitty. Not surviving a restart is kind of a show-stopper.
Is there a way to tell the image not to update opencart on every single restart?

**Comment by carrodher** [comment]
Hi, sorry for the delay in solving this issue, we have a wide catalog of applications and we need to set different priorities. Regarding this specific issue, I just raised the priority of our internal task, so the team is going to work on it probably during the next week(s).
