### ISSUE TITLE
Persitence Volumes on FreeNAS

### ISSUE THREAD

**Issue by Lenny-ai** [bitnami/bitnami-docker-opencart#77]
**Description**

I am trying to put my persitence volumes onto FreeNAS. Since FreeNAS automatically sets permissions and ownership of files and folders to 1001:1001 . As a consequence the opencart service is stopped by permission errors. 
In order to sort permissions out I am trying to use USER: 1001 in my docker-compose file.

I need help to either 
A) enforcing user 1001 as root
or 
B) enabling opencart to build with user: 1001
or
C) any other creative advice to store persitence volumes on FreeNAS

**Steps to reproduce the issue:**

1. add "User: 1001" to the opencart service

**Describe the results you received:**

During build of opencart service I am getting:  /bin/bash: /app-entrypoint.sh: Permission denied

**Describe the results you expected:**

I expected a build without errors. But I understand the opencart might need root permission of files and folders. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 97
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: pzy5122b03malq5wkc3unpzww
  Is Manager: true
  ClusterID: j6je2nbegz2n4qu3hm4mi3jc7
  Managers: 1
  Nodes: 5
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-40-generic
 Operating System: Linux Mint 19.3
 OSType: linux
 Architecture: x86_64
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @Lenny-ai, thank you for opening this issue, you are right, opencart container is not ready to run as non-root user yet, we are currently moving our catalog to non-root. Unfortunately, we can not give you an ETA for opencart container, however, I made a workaround. 

First, you must build your own image using:
```
FROM bitnami/opencart:3

ENV NAMI_PREFIX="/.nami"

RUN chmod -R g+rwx,o+rwx $(ls | grep -e ".*\.sh") && \
  cp -r /root/.nami /.nami && \
  mkdir -p /bitnami && \
  chmod -R g+rwX,o+rwX /.nami /opt/bitnami /bitnami
```
Then you must also modify the configuration logic in `/.nami/components/com.bitnami.opencart/main.js`, I already did, you can find the new file in [opencart.tar.gz](https://github.com/bitnami/bitnami-docker-opencart/files/4292964/opencart.tar.gz) attached.

All the needed files are in [opencart.tar.gz](https://github.com/bitnami/bitnami-docker-opencart/files/4292964/opencart.tar.gz).

**Comment by Lenny-ai** [comment]
Hi @dani8art , thanks for picking up this issue and providing the solution! Most appreciated are the files.
However, the following response appears on `docker-compose up --build`:

opencart_1  | nami    INFO  Initializing apache
opencart_1  | nami    INFO  apache successfully initialized`
opencart_1  | nami    INFO  Initializing php
opencart_1  | nami    INFO  php successfully initialized
opencart_1  | nami    INFO  Initializing mysql-client
opencart_1  | nami    INFO  mysql-client successfully initialized
opencart_1  | nami    INFO  Initializing opencart
opencart_1  | opencar INFO  Preparing webserver environment...
opencart_1  | opencar INFO  Preparing PHP environment...
opencart_1  | Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/opencart/.restored'
octest_opencart_1 exited with code 1

I assume you did not get this message. Could you please advice on how to resolve this one.

**Comment by dani8art** [comment]
Yes, It is because you already have a volume created, please remove it and try again.
```
$ docker-compose down -v
$ docker-compose up -d
```

**Comment by Lenny-ai** [comment]
Ok, that solved the error above.

However, there is another problem is popping up. Although the opencart service has specified:

`    depends_on:
      - mariadb`

It doesn't seem to wait for the mariadb service to be completely up and fails to connect.

Is there another way to prioritize container building other than depends_on ?

**Opencart error.log:**
2020-03-13 15:29:44 - PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in /opt/bitnami/opencart/system/library/db/mysqli.php on line 7
2020-03-13 15:29:44 - PHP Warning:  DB\MySQLi::__construct(): Couldn't fetch mysqli in /opt/bitnami/opencart/system/library/db/mysqli.php on line 10
2020-03-13 15:29:44 - PHP Warning:  DB\MySQLi::__construct(): Couldn't fetch mysqli in /opt/bitnami/opencart/system/library/db/mysqli.php on line 10

**Terminal output:**
mariadb_1   | mariadb 15:29:28.79 
frontend    | app-entrypoint.sh 15:29:29.32 
mariadb_1   | mariadb 15:29:28.79 Welcome to the Bitnami mariadb container
frontend    | app-entrypoint.sh 15:29:29.32 Welcome to the Bitnami opencart container
frontend    | app-entrypoint.sh 15:29:29.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
frontend    | app-entrypoint.sh 15:29:29.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
frontend    | app-entrypoint.sh 15:29:29.33 Send us your feedback at containers@bitnami.com
frontend    | app-entrypoint.sh 15:29:29.33 
mariadb_1   | mariadb 15:29:28.79 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1   | mariadb 15:29:28.79 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1   | mariadb 15:29:28.80 Send us your feedback at containers@bitnami.com
mariadb_1   | mariadb 15:29:28.80 
mariadb_1   | mariadb 15:29:28.80 INFO  ==> ** Starting MariaDB setup **
mariadb_1   | mariadb 15:29:28.88 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1   | mariadb 15:29:28.89 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1   | mariadb 15:29:28.89 INFO  ==> Initializing mariadb database
mariadb_1   | mariadb 15:29:29.16 DEBUG ==> Ensuring expected directories/files exist
frontend    | app-entrypoint.sh 15:29:29.34 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1   | mariadb 15:29:29.72 DEBUG ==> Creating main configuration file
mariadb_1   | mariadb 15:29:29.99 INFO  ==> Using persisted data
mariadb_1   | mariadb 15:29:30.00 INFO  ==> Running mysql_upgrade
mariadb_1   | mariadb 15:29:30.01 INFO  ==> Starting mariadb in background
mariadb_1   | 2020-03-13 15:29:30 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.22-MariaDB) starting as process 141 ...
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Using Linux native AIO
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Uses event mutexes
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Number of pools: 1
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1   | 2020-03-13 15:29:30 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=63336154
frontend    | nami    INFO  Initializing apache
frontend    | nami    INFO  apache successfully initialized
mariadb_1   | 2020-03-13 15:29:32 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1   | 2020-03-13 15:29:32 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mariadb_1   | 2020-03-13 15:29:32 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1   | 2020-03-13 15:29:32 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1   | 2020-03-13 15:29:32 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
frontend    | nami    INFO  Initializing php
frontend    | nami    INFO  php successfully initialized
mariadb_1   | 2020-03-13 15:29:34 0 [Note] InnoDB: 10.3.22 started; log sequence number 63336163; transaction id 95161
mariadb_1   | 2020-03-13 15:29:35 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Recovering after a crash using tc.log
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Starting crash recovery...
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Crash recovery finished.
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Server socket created on IP: '127.0.0.1'.
mariadb_1   | 2020-03-13 15:29:35 0 [Note] InnoDB: Buffer pool(s) load completed at 200313 15:29:35
mariadb_1   | 2020-03-13 15:29:35 0 [Warning] 'proxies_priv' entry '@% root@88d3f376b78b' ignored in --skip-name-resolve mode.
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Reading of all Master_info entries succeeded
mariadb_1   | 2020-03-13 15:29:35 0 [Note] Added new Master_info '' to hash table
mariadb_1   | 2020-03-13 15:29:35 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1   | Version: '10.3.22-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb_1   | Phase 1/7: Checking and upgrading mysql database
mariadb_1   | Processing databases
mariadb_1   | mysql
mariadb_1   | mysql.column_stats                                 OK
mariadb_1   | mysql.columns_priv                                 OK
mariadb_1   | mysql.db                                           OK
mariadb_1   | mysql.event                                        OK
mariadb_1   | mysql.func                                         OK
mariadb_1   | mysql.gtid_slave_pos                               OK
mariadb_1   | mysql.help_category                                OK
mariadb_1   | mysql.help_keyword                                 OK
mariadb_1   | mysql.help_relation                                OK
mariadb_1   | mysql.help_topic                                   OK
mariadb_1   | mysql.host                                         OK
mariadb_1   | mysql.index_stats                                  OK
mariadb_1   | mysql.innodb_index_stats                           OK
mariadb_1   | mysql.innodb_table_stats                           OK
mariadb_1   | mysql.plugin                                       OK
mariadb_1   | mysql.proc                                         OK
mariadb_1   | mysql.procs_priv                                   OK
mariadb_1   | mysql.proxies_priv                                 OK
mariadb_1   | mysql.roles_mapping                                OK
mariadb_1   | mysql.servers                                      OK
mariadb_1   | mysql.table_stats                                  OK
mariadb_1   | mysql.tables_priv                                  OK
mariadb_1   | mysql.time_zone                                    OK
mariadb_1   | mysql.time_zone_leap_second                        OK
mariadb_1   | mysql.time_zone_name                               OK
mariadb_1   | mysql.time_zone_transition                         OK
mariadb_1   | mysql.time_zone_transition_type                    OK
mariadb_1   | mysql.transaction_registry                         OK
mariadb_1   | mysql.user                                         OK
mariadb_1   | Phase 2/7: Installing used storage engines... Skipped
mariadb_1   | Phase 3/7: Fixing views
frontend    | nami    INFO  Initializing mysql-client
frontend    | nami    INFO  mysql-client successfully initialized
**mariadb_1   | Phase 4/7: Running 'mysql_fix_privilege_tables'
frontend    | nami    INFO  Initializing opencart**
frontend    | apache  TRACE Skipping reload: com.bitnami.apache not running
frontend    | apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
frontend    | apache  TRACE code: 0
frontend    | apache  TRACE stdout:
frontend    | 
frontend    | apache  TRACE stderr:
frontend    | 
frontend    | opencar INFO  Preparing webserver environment...
frontend    | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
frontend    | opencar INFO  Preparing PHP environment...
frontend    | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/config.php to /opt/bitnami/opencart/config.php
frontend    | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/admin/config.php to /opt/bitnami/opencart/admin/config.php
frontend    | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/admin/view/stylesheet/bootstrap.css to /opt/bitnami/opencart/admin/view/stylesheet/bootstrap.css
frontend    | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/image to /opt/bitnami/opencart/image
frontend    | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/system/storage to /opt/bitnami/opencart/system/storage
frontend    | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
frontend    | opencar INFO  Upgrading OpenCart...
frontend    | opencar DEBUG ==> Setting timeout to 120000 miliseconds
frontend    | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1:8080/install/index.php?route=upgrade/upgrade
frontend    | Server returned status code 500 from http://127.0.0.1:8080/install/index.php?route=upgrade/upgrade
frontend    | nami    TRACE Error: Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1:8080/install/index.php?route=upgrade/upgrade
frontend    | Server returned status code 500 from http://127.0.0.1:8080/install/index.php?route=upgrade/upgrade
frontend    |     at Browser.exec (/opt/bitnami/nami/node_modules/nami-core/lib/browser/index.js:447:15)
frontend    |     at Component.$app.postInstallation (/.nami/components/com.bitnami.opencart/main.js:103:31)
frontend    |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
frontend    |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
frontend    |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
frontend    |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
frontend    |     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
frontend    |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
frontend    |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
frontend    |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:524:30)
frontend    |     at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:748:14)
frontend    |     at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
frontend    |     at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
frontend    |     at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
frontend    |     at Module._compile (module.js:652:30)
frontend    |     at Object.Module._extensions..js (module.js:663:10)
frontend exited with code 1
mariadb_1   | Phase 5/7: Fixing table and database names
mariadb_1   | Phase 6/7: Checking and upgrading tables
mariadb_1   | Processing databases

**Comment by Lenny-ai** [comment]
I added:
`restart: on-failure` to the opencart service
as a quick-fix. Not very nice though. Can you suggest a better way?

**Comment by Lenny-ai** [comment]
And now I get:

frontend    | nami    INFO  Initializing apache
frontend    | Error loading JSON file EACCES: permission denied, open '/apache-inputs.json'
frontend    | nami    TRACE Error: Error loading JSON file EACCES: permission denied, open '/apache-inputs.json'
frontend    |     at ComponentParser._getJsonData (/opt/bitnami/nami/node_modules/cmd-parser/index.js:410:13)
frontend    |     at ComponentParser._getJsonData (/opt/bitnami/nami/node_modules/nami-core/lib/components/component-parser.js:35:24)
frontend    |     at ComponentParser.parseJSON (/opt/bitnami/nami/node_modules/cmd-parser/index.js:414:25)
frontend    |     at Option.optionFileOpts.callback (/opt/bitnami/nami/node_modules/cmd-parser/index.js:475:13)
frontend    |     at Option.setValue (/opt/bitnami/nami/node_modules/cmd-parser/index.js:191:12)
frontend    |     at ComponentParser.parseFlags (/opt/bitnami/nami/node_modules/cmd-parser/index.js:273:16)
frontend    |     at ComponentParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:744:25)
frontend    |     at Manager._populateObjectFromCmdFlags (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:250:16)
frontend    |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:282:10)
frontend    |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
frontend exited with code 1

**Comment by dani8art** [comment]
Hi, the error I can see is the following 
> frontend | Error executing 'postInstallation': Server returned status code 500 from

This is actually a bug in our configuration logic that you could workaround modifying the `main.js`
```diff
    if (port) {
      browser.visit(`http://127.0.0.1:${port}/install/index.php?route=upgrade/upgrade`);
    } else {
      browser.visit('http://127.0.0.1/install/index.php?route=upgrade/upgrade');
    }
-    browser.visit('http://127.0.0.1/install/index.php?route=upgrade/upgrade');
``` 

The other errors I cannot reproduce them. I did the following using the file attached:

```bash
## clean up the environment
$ docker-compose down -v

## build the images and up the containers
$ docker-compose up -d --build

## all is working fine
## then down the containers only to simulate data already present
$ docker-compose down

## start containers again
$ docker-compose up -d

## All is working fine
$ docker-compose logs -f opencart
# Attaching to opencart_opencart_1
# opencart_1  | app-entrypoint.sh 17:58:43.12 
# opencart_1  | app-entrypoint.sh 17:58:43.12 Welcome to the Bitnami opencart container
# opencart_1  | app-entrypoint.sh 17:58:43.12 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
# opencart_1  | app-entrypoint.sh 17:58:43.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
# opencart_1  | app-entrypoint.sh 17:58:43.12 Send us your feedback at containers@bitnami.com
# opencart_1  | app-entrypoint.sh 17:58:43.12 
# opencart_1  | app-entrypoint.sh 17:58:43.13 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
# opencart_1  | nami    INFO  Initializing apache
# opencart_1  | nami    INFO  apache successfully initialized
# opencart_1  | nami    INFO  Initializing php
# opencart_1  | nami    INFO  php successfully initialized
# opencart_1  | nami    INFO  Initializing mysql-client
# opencart_1  | nami    INFO  mysql-client successfully initialized
# opencart_1  | nami    INFO  Initializing opencart
# opencart_1  | apache  TRACE Skipping reload: com.bitnami.apache not running
# opencart_1  | apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
# opencart_1  | apache  TRACE code: 0
# opencart_1  | apache  TRACE stdout:
# opencart_1  | 
# opencart_1  | apache  TRACE stderr:
# opencart_1  | 
# opencart_1  | opencar INFO  Preparing webserver environment...
# opencart_1  | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
# opencart_1  | opencar INFO  Preparing PHP environment...
# opencart_1  | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/config.php to /opt/bitnami/opencart/config.php
# opencart_1  | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/admin/config.php to /opt/bitnami/opencart/admin/config.php
# opencart_1  | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/admin/view/stylesheet/bootstrap.css to /opt/bitnami/opencart/admin/view/stylesheet/bootstrap.css
# opencart_1  | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/image to /opt/bitnami/opencart/image
# opencart_1  | opencar TRACE [restorePersistedData] Restoring /bitnami/opencart/system/storage to /opt/bitnami/opencart/system/storage
# opencart_1  | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
# opencart_1  | opencar INFO  Upgrading OpenCart...
# opencart_1  | opencar DEBUG ==> Setting timeout to 120000 miliseconds
# opencart_1  | opencar INFO  ###### my port: 8080
# opencart_1  | opencar INFO  Upgrade finished
# opencart_1  | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
# opencart_1  | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
# opencart_1  | opencar INFO 
# opencart_1  | opencar INFO  ########################################################################
# opencart_1  | opencar INFO   Installation parameters for opencart:
# opencart_1  | opencar INFO     Persisted data and properties have been restored.
# opencart_1  | opencar INFO     Any input specified will not take effect.
# opencart_1  | opencar INFO   This installation requires no credentials.
# opencart_1  | opencar INFO  ########################################################################
# opencart_1  | opencar INFO 
# opencart_1  | nami    INFO  opencart successfully initialized
# opencart_1  | app-entrypoint.sh 17:59:12.61 INFO  ==> Starting opencart... 
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:00 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=2 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:02 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=3 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:03 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=4 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:04 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=5 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:05 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=6 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:06 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=7 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:07 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=8 HTTP/1.1" 200 106
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:08 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=9 HTTP/1.1" 200 107
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:09 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=10 HTTP/1.1" 200 108
# opencart_1  | 127.0.0.1 - - [16/Mar/2020:17:59:10 +0000] "POST /install/index.php?route=upgrade/upgrade/next&step=11 HTTP/1.1" 200 88
```

Please, note that I'm executing both containers as `1001` user.
[opencart-01.tar.gz](https://github.com/bitnami/bitnami-docker-opencart/files/4339665/opencart-01.tar.gz)
