### ISSUE TITLE
How to persist modified colum type in mariadb?

### ISSUE THREAD

**Issue by Lenny-ai** [bitnami/bitnami-docker-opencart#78]
**Description**

For some reason I would like to change the column type from varchar(255) to varchar(21000). I manage to do so inside a running container. However, after rebuilding the conatiner with docker-compose this change is lost. I am using a persitence volume for the mariadb which works fine with the data but not with the change in the column type. 

Please advise on where to put the sql command. Any other creative solution is welcome too.

PS
In the docker-compose.yml file I would like to use command instead of build to apply the changes.

**Steps to reproduce the issue:**

1. docker-compose up --build the standard configuration with persitence volumes
2. exec bash into the mariadb container
3. mysql -u bn_opencart bitnami_opencart <<_EOF_
  ALTER TABLE oc_customer_search MODIFY keyword varchar(21000) not null;
_EOF_

**Describe the results you received:**

The changes are applied while the container is runnning. But they are lost after docker-compose down and a rebuild with docker-compose up --build.

**Describe the results you expected:**

Persist changes to colum type after docker-compose down and docker-compose up --build

**Version**
I believe the version is not needed for this issue. If it is needed I provide the info later on.

**Comment by dani8art** [comment]
@Lenny-ai thank you for opening this issue, I will try to reproduce it. I have a question regarding `docker-compose up --build`, why do you need it here?

**Comment by dani8art** [comment]
I've noticed that you are not committing the changes in the schema, please try:
```
mysql -u bn_opencart bitnami_opencart <<EOF
ALTER TABLE oc_customer_search MODIFY keyword varchar(21000) not null;
commit;
EOF
```

**Comment by Lenny-ai** [comment]
Hi @dani8art, 
thanks for your replies. 

> `docker-compose up --build`, why do you need it here?
Because I am building the opencart container using a Dockerfile

> I've noticed that you are not committing the changes in the schema
I tried it but it did not solve the issue. 
In the meantime I figured out that the changes in the schema are always lost after `docker-compose down`. A `docker-compose up --build` or `docker-compose up` afterwards creates the default column type varchar(255). 

However the changes in the schema are persisted when stopping the container with `docker-compose stop` and restarting with `docker-compose up` or even `docker-compose start`.

That behaviour makes me think, that there may be a difference in initializing the database when the container is build from scratch or restarted.

I had a look in the rootfs folder of mariadb. There is a file called libmysql.sh. I there an option for you to create a function to make schema changes by passing a dictionary as an environments variable? 
Example: `{'table_name':'oc_customer_search', ''column_name:'keyword','column_type':'varchar(21000)'}`

Just to mention. The data in the columns and tables is perfectly persisted ... so no issue with that.

**Comment by dani8art** [comment]
Sorry @Lenny-ai, I think I didn't explain well before. When you do a write action in a MySQL DB you must commit your changes executing `commit;` in your script. Anyway, even adding this I was able to reproduce it.

```bash
## clean up the environment
$ docker-compose down -v

## up environment
$ docker-compose up -d 

## let's wait until deployment is ready.
## list table schema
$ docker-compose exec mariadb mysql -u bn_opencart bitnami_opencart -e "SELECT COLUMN_NAME,COLUMN_TYPE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH \
  FROM INFORMATION_SCHEMA.COLUMNS \
  WHERE table_name='oc_customer_search';"
# +--------------------+--------------+-----------+--------------------------+
# | COLUMN_NAME        | COLUMN_TYPE  | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH |
# +--------------------+--------------+-----------+--------------------------+
# | customer_search_id | int(11)      | int       |                     NULL |
# | store_id           | int(11)      | int       |                     NULL |
# | language_id        | int(11)      | int       |                     NULL |
# | customer_id        | int(11)      | int       |                     NULL |
# | keyword            | varchar(255) | varchar   |                      255 |
# | category_id        | int(11)      | int       |                     NULL |
# | sub_category       | tinyint(1)   | tinyint   |                     NULL |
# | description        | tinyint(1)   | tinyint   |                     NULL |
# | products           | int(11)      | int       |                     NULL |
# | ip                 | varchar(40)  | varchar   |                       40 |
# | date_added         | datetime     | datetime  |                     NULL |
# +--------------------+--------------+-----------+--------------------------+

## Update schema. NOTE: we are adding commit;
$ docker-compose exec mariadb mysql -u bn_opencart bitnami_opencart -e "ALTER TABLE oc_customer_search MODIFY keyword varchar(21000) not null; commit;"

## shutdown the environment up again
$ docker-compose down
$ docker-compose up -d --build

## list table schema
$ docker-compose exec mariadb mysql -u bn_opencart bitnami_opencart -e "SELECT COLUMN_NAME,COLUMN_TYPE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH \
  FROM INFORMATION_SCHEMA.COLUMNS \
  WHERE table_name='oc_customer_search';"
# +--------------------+----------------+-----------+--------------------------+
# | COLUMN_NAME        | COLUMN_TYPE    | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH |
# +--------------------+----------------+-----------+--------------------------+
# | customer_search_id | int(11)        | int       |                     NULL |
# | store_id           | int(11)        | int       |                     NULL |
# | language_id        | int(11)        | int       |                     NULL |
# | customer_id        | int(11)        | int       |                     NULL |
# | keyword            | varchar(21000) | varchar   |                    21000 |
# | category_id        | int(11)        | int       |                     NULL |
# | sub_category       | tinyint(1)     | tinyint   |                     NULL |
# | description        | tinyint(1)     | tinyint   |                     NULL |
# | products           | int(11)        | int       |                     NULL |
# | ip                 | varchar(40)    | varchar   |                       40 |
# | date_added         | datetime       | datetime  |                     NULL |
# +--------------------+----------------+-----------+--------------------------+

## All seems to be fine but actually if wait until opencart setup is finished 
$ docker-compose exec mariadb mysql -u bn_opencart bitnami_opencart -e "SELECT COLUMN_NAME,COLUMN_TYPE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH \
  FROM INFORMATION_SCHEMA.COLUMNS \
  WHERE table_name='oc_customer_search';"
# +--------------------+--------------+-----------+--------------------------+
# | COLUMN_NAME        | COLUMN_TYPE  | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH |
# +--------------------+--------------+-----------+--------------------------+
# | customer_search_id | int(11)      | int       |                     NULL |
# | store_id           | int(11)      | int       |                     NULL |
# | language_id        | int(11)      | int       |                     NULL |
# | customer_id        | int(11)      | int       |                     NULL |
# | keyword            | varchar(255) | varchar   |                      255 |
# | category_id        | int(11)      | int       |                     NULL |
# | sub_category       | tinyint(1)   | tinyint   |                     NULL |
# | description        | tinyint(1)   | tinyint   |                     NULL |
# | products           | int(11)      | int       |                     NULL |
# | ip                 | varchar(40)  | varchar   |                       40 |
# | date_added         | datetime     | datetime  |                     NULL |
# +--------------------+--------------+-----------+--------------------------+
```

I've realized in our configuration logic we are updating opencart through the web interface every time we set up the container as you can see in `/root/.nami/components/com.bitnami.opencart/main.js`
```js
...
    $app.info('Upgrading OpenCart...');
    const browser = new $Browser();
    browser.waitDuration = '720s';
    browser.xmlHttpRequestTimeout = $app.httpTimeout * 1000;
    $app.debug(`==> Setting timeout to ${browser.xmlHttpRequestTimeout} miliseconds`);

    if (port) {
      browser.visit(`http://127.0.0.1:${port}/install/index.php?route=upgrade/upgrade`);
    } else {
      browser.visit('http://127.0.0.1/install/index.php?route=upgrade/upgrade');
    }
    browser.visit('http://127.0.0.1/install/index.php?route=upgrade/upgrade');
    browser.press('Continue').exec({abortOnError: true});
    browser.wait('span.text-success'); // eslint-disable-line bitnami-components/no-wait
    $app.info('Upgrade finished');
...
```

That means, we could say that we have an "issue" here, but an issue that actually isn't. I mean, this is the correct behavior of opencart when you do an update, if we would fix this configuration logic, what would happen when you manually do an update of the database? you will lose your changes again. 

Apart from that, I would say is not recommended to modify web application predefined schemas, if you really needed I would encourage you to open a ticket or try to find help in the opencart community they are going to help you better the know better how their application and its database updates work in the end.
