### ISSUE TITLE
custom opencart extensions

### ISSUE THREAD

**Issue by Fuseteam** [bitnami/bitnami-docker-opencart#80]
i'm currently trying to develop a custom payment extension for a local payment processor
i have attempted [this tutorial](https://webocreation.com/blog/ocmod-documentation/) to get something to should up in the admin section but no dice grepping inside the container i cannot find where the extension is, is there something i should do differently with the docker container, is the tutorial outdated or am i doing something wrong?
[test.ocmod.zip](https://github.com/bitnami/bitnami-docker-opencart/files/4589051/test.ocmod.zip)

**Comment by juan131** [comment]
Hi @Fuseteam 

Bitnami is not maintaining that blog/tutorial so we cannot respond on whether that's updated or not.

Regarding the file structure on this container regarding other OpenCart solutions, i'd like to highlight a couple of things:

- This container has all the Opencart files under the `/opt/bitnami/opencart/` directory
- However, some of the files/directories under `/opt/bitnami/opencart/` are symbolic links to `bitnami/opencart/`, the directory where data is persisted (see https://github.com/bitnami/bitnami-docker-opencart#persisting-your-application for more information). These files directories are:
    - `config.php` file.
    - `admin/config.php` file.
    - `image` directory.
    - `system/storage` directory.

Therefore, whenever you need to edit sth that's persisted, you need to modify the files at `bitnami/opencart/`.

**Comment by Fuseteam** [comment]
hmm interesting, i suspect extension should be persisted so it must be somewhere in system perhaps system storage, if i can at least get something visible in the gui that would be great, does bitnami has some tutorial on developing custom opencart extensions using the bitnami docker container?

**Comment by juan131** [comment]
Hi @Fuseteam 

> does bitnami has some tutorial on developing custom opencart extensions using the bitnami docker container?

I am afraid we don't have such a tutorial. I will share this issue with the docs team though, so they can consider to develop one tutorial in the future.

> edit:ohwkay looking in /opt/bitnami/opencart/admin i can see there are lot more files in here. i'm starting to see what you mean, now i just need to figure out what it means for installing custom extensions

Please do not hesitate to let us know if you require any help to understand the file structure.

**Comment by Fuseteam** [comment]
> I am afraid we don't have such a tutorial. I will share this issue with the docs team though, so they can consider to develop one tutorial in the future.
oof that's too bad i kinda need some help understanding how these extensions should be made

> Please do not hesitate to let us know if you require any help to understand the file structure.
so at this point i can see that a custom payment extension uses the paths
/opt/bitnami/opencart/admin/controller/extension/payment/extenami.php
/opt/bitnami/opencart/admin/view/template/extension/payment/extenami.twig
/opt/bitnami/opencart/admin/language/en-gb/extentent/payment/extenami.php

i suppose if i want to persist it i would need to symlink to /bitnami/opencart would that require some modification to the image on my side

on that note trying to install via the gui doesn't seem to place the files mentioned in the paths above, tho i have no idea if that's an issue with the image or if i did something wrong

**Comment by juan131** [comment]
Hi @Fuseteam  

> so at this point i can see that a custom payment extension uses the paths
> /opt/bitnami/opencart/admin/controller/extension/payment/extenami.php
> /opt/bitnami/opencart/admin/view/template/extension/payment/extenami.twig
> /opt/bitnami/opencart/admin/language/en-gb/extentent/payment/extenami.php
>
> i suppose if i want to persist it i would need to symlink to /bitnami/opencart would that require some modification to the image on my side

None of these files are persisted. Therefore, you don't to create any symlink to `bitnami/opencart`.

On the other hand, since these files are not persisted, I highly recommend to build your custom image based on bitnami's one to ensure the extension is shipped by default. Otherwise, you'll have to install the extension every time the container gets restarted.

**Comment by Fuseteam** [comment]
> On the other hand, since these files are not persisted, I highly recommend to build your custom image based on bitnami's one to ensure the extension is shipped by default. Otherwise, you'll have to install the extension every time the container gets restarted.

yeah i kinda was expecting that, the symlink would be lost on container restart i suppose

any tips on testing if plugins are installable via the UI with the container? for now that doesn't seem to work on my end

**Comment by juan131** [comment]
Hi @Fuseteam 

Could you provide, step by step, the instructions you followed to install the extension through the UI?
Could you also share the logs you obtain from the container when the extension fails to install?

**Comment by Fuseteam** [comment]
i upload [this zip](https://github.com/bitnami/bitnami-docker-opencart/files/4589051/test.ocmod.zip) via the admin interface but i didn't see it in the list of extensions nor in modifications
where can i find the logs?

**Comment by juan131** [comment]
@Fuseteam you might get more information from the `/opt/bitnami/opencart/system/storage/logs/error.log` log file:

```bash
docker-compose exec opencart cat /opt/bitnami/opencart/system/storage/logs/error.log
```

**Comment by Fuseteam** [comment]
looks like error log is empty.......

**Comment by juan131** [comment]
Do you obtain anything trough the Admin panel? Browse to "System" -> "Maintenance" -< "Error Logs":

![Screenshot 2020-05-15 at 08 35 59](https://user-images.githubusercontent.com/6740773/82019565-bfbff080-9687-11ea-9e78-59ab09b12a16.png)

Does the "Extension Installer" shows you any information about the reasons why the extension can't be installed?

**Comment by Fuseteam** [comment]
the "extensions installer" tells me it is successfully installed no errors whatsoever

**Comment by juan131** [comment]
Hi @Fuseteam 

I compared your extension with other existing in the Opencart marketplace (e.g. Paypal). While this is the file structure in the Paypal one (after unziping):

```console
upload/
├── admin
(...)
├── catalog
(...)
└── system
(...)
```

This is yours:

```console
test
└── upload
    └── admin
        ├── controller
        │   └── extension
        │       └── payment
        │           └── test.php
        ├── language
        │   └── english
        │       └── payment
        │           └── test.php
        └── view
            └── template
                └── extension
                    └── payment
                        └── test.tpl

12 directories, 3 files
```

As you can see, when you uncompress your zip, "upload" is a subdirectory, while it's the "root" directory in the extension I got from the marketplace. Could you fix that?

**Comment by Fuseteam** [comment]
ah i did not notice that, that actually fixed it. Thank you!
[test.ocmod.zip](https://github.com/bitnami/bitnami-docker-opencart/files/4644008/test.ocmod.zip)

**Comment by juan131** [comment]
Great!! So I guess you were able to install the extensions. Didn't you?
Please let us know if there is anything else we can help you with.

**Comment by Fuseteam** [comment]
yes i was able to install the extension getting the upload directory as the root directory solved that, thank you
i'm currently putting the finishing touches on the extension for now i am looking into how to handle the parameters the payment gateway host sends me

**Comment by juan131** [comment]
Great to hear that @Fuseteam !! 

For that kind of customisations of the application itself, you might find more information in Opencart forums such as https://forum.opencart.com

However,, please do not hesitate to let us know if you have any issue with the container.

**Comment by Fuseteam** [comment]
@juan131 alright thanks a lot for the help so far :+1:
