### ISSUE TITLE
Adding domain and subdomain OPENCART_HOST

### ISSUE THREAD

**Issue by gilbertobr** [bitnami/bitnami-docker-opencart#82]
Would it be possible to add 2 domains to OPENCART_HOST?
If so, how would it be?
Ex:
 "OPENCART_HOST=test.domain.com.br,www.domain.com.br",

**Comment by javsalgar** [comment]
Hi,

I don't think we currently have support for that. Could you explain your use case in more detail?

**Comment by gilbertobr** [comment]
I understand,
the idea would be of the end customer.
Access the store through 2 different links in case
using www.domain.com.br and test.domain.com.br.

I believe it would be very useful, as the customer could access it through 2 different routes.

**Comment by javsalgar** [comment]
Hi,

According to https://forum.opencart.com/viewtopic.php?t=152928 this should be done using the multi-store setting. Did you try checking that feature?
