### ISSUE TITLE
Deployment is not created

### ISSUE THREAD

**Issue by menih** [bitnami/bitnami-docker-opencart#83]
Installed latest Chart (7.0.19). Also tried earlier version. In both cases, opencart deployment is not created. opencart-mariadb is created and works.

**Comment by marcosbc** [comment]
Hi @menih, note that OpenCart requires you to set a host when deploying, and it will not deploy until you do. These were the Helm chart deployment notes in my case:

```console
$ helm install myopencart bitnami/opencart
NAME: myopencart
LAST DEPLOYED: Mon Jul 27 17:59:58 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
###############################################################################
### ERROR: You did not provide an external host in your 'helm install' call ###
###############################################################################

This deployment will be incomplete until you configure OpenCart with a resolvable
host. To configure OpenCart with the URL of your service:

1. Get the OpenCart URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w myopencart'

  export APP_HOST=$(kubectl get svc --namespace default myopencart --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  export APP_PASSWORD=$(kubectl get secret --namespace default myopencart -o jsonpath="{.data.opencart-password}" | base64 --decode)
  export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace default myopencart-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)

2. Complete your OpenCart deployment by running:

  helm upgrade myopencart bitnami/opencart \
    --set opencartHost=$APP_HOST,opencartPassword=$APP_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD
```

Specifically, see this warning:

```console
This deployment will be incomplete until you configure OpenCart with a resolvable
host. To configure OpenCart with the URL of your service:

1. ...
2. ...
```

**Comment by menih** [comment]
I followed the instructions. I got the following error:

>     --set
opencartHost=$APP_HOST,opencartPassword=$APP_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD
Error: UPGRADE FAILED: cannot patch "opencart-opencart" with kind
PersistentVolumeClaim: PersistentVolumeClaim "opencart-opencart" is
invalid: spec: Forbidden: is immutable after creation except
resources.requests for bound claims && cannot patch "opencart-mariadb" with
kind StatefulSet: StatefulSet.apps "opencart-mariadb" is invalid: spec:
Forbidden: updates to statefulset spec for fields other than 'replicas',
'template', and 'updateStrategy' are forbidden

**Comment by marcosbc** [comment]
@menih It looks like those issues are happening because of installing a deployment to a same namespace, or because of K8s cluster or Helm being too old.

Could you please provide the following info?

* Re-deploy with a different deployment name, does it work?
* The information requested in the [New issue](https://github.com/bitnami/charts/issues/new?assignees=&labels=&template=bug_report.md&title=) form for Bitnami charts
* The full command so we can troubleshoot on our side if there's any issue

**Comment by menih** [comment]
Yep. That worked! thanks!
