### ISSUE TITLE
HTTPS url is HTTP in php configs

### ISSUE THREAD

**Issue by ergbouncex** [bitnami/bitnami-docker-opencart#88]
**Description**

Both the config files listed below have "http" defined for https.
```
/opt/bitnami/opencart/admin/config.php
/opt/bitnami/opencart/config.php
```

There is an older bug [55](https://github.com/bitnami/bitnami-docker-opencart/issues/55)
that describes the same issue. 

**Version**
I am using this image: [eea095b40e27](https://hub.docker.com/layers/bitnami/opencart/latest/images/sha256-eea095b40e2759141364ac1c625889971b490ee788138dc0ed6e2fea841a2cfd?context=explore)

**Comment by carrodher** [comment]
Thanks for reporting this issue, as there is an already existing thread in the old ticket I am going to close this one to avoid duplications.
