### ISSUE TITLE
HTTPS disabled but it's still used for logins

### ISSUE THREAD

**Issue by virgil9306** [bitnami/bitnami-docker-opencart#90]
**Description**

When HTTPS is **disabled**, trying to log in via `http://localhost:8080/admin/` POSTs me to `https://localhost/admin/index.php?route=common/login`. I should be using `http` and **not** `https` here.

The opposite issue of https://github.com/bitnami/bitnami-docker-opencart/issues/88 .

**Steps to reproduce the issue:**

1. Run docker container on `minikube` locally
2. `minikube port-forward <POD_NAME> 8080:8080`

**Describe the results you received:**

1. Visiting `http://localhost:8080/admin/` works OK
2. But after trying to log in, the page changes to `https://localhost/admin/index.php?route=common/login`.
3. But that page is not available (there is nothing on HTTPS port on my `localhost`).

**Describe the results you expected:**

I configured HTTPS as off: `OPENCART_ENABLE_HTTPS` to `"no"` (this is default behavior). I expect that it will not use HTTPS for any URLs.

**Additional information you deem important (e.g. issue happens only occasionally):**

- **I tried to resolve it by doing the following:**
  - I wanted to create my own image of this Dockerfile to manually change `define('HTTPS_SERVER', 'http://localhost/');` in the `/opt/bitnami/opencart/config.php` file, but I guess that file is generated on runtime, so I could not change it!

**Version**

- Output of `docker version`:

```
Client:
 Debug Mode: false

Server:
 Containers: 28
  Running: 3
  Paused: 0
  Stopped: 25
 Images: 170
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.154-boot2docker
 Operating System: Boot2Docker 19.03.5 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.856GiB
 Name: default
 ID: IVWH:5IFF:Q45U:7L7Z:2LPP:OPO7:QSQK:O2ET:HVWM:Z3FN:NR2G:46HV
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Username: <MY_USERNAME>
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 28
  Running: 3
  Paused: 0
  Stopped: 25
 Images: 170
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.154-boot2docker
 Operating System: Boot2Docker 19.03.5 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.856GiB
 Name: default
 ID: IVWH:5IFF:Q45U:7L7Z:2LPP:OPO7:QSQK:O2ET:HVWM:Z3FN:NR2G:46HV
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Username: <REDACTED>
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* I am NOT mapping any HTTPS ports locally to the container, so it will fail (intended).
* I tried running on Minikube
* I also tried running the image on locally on OSX using `docker machine` and running the image normally, and port-forwarding `8080` of localhost to `8080` of the container using VirtualBox config settings.

**Comment by FraPazGal** [comment]
Hi @virgil9306,

I have been able to reproduce the issue and I have created an internal task to solve it. I can't give you an ETA at the moment but we would update this issue as soon as possible.

**Comment by virgil9306** [comment]
Thanks so much for looking into it. This is the only blocker for me and
would be happy to use OpenCart once it’s solved.

2020年11月10日(火) 3:15 Francisco de Paz Galán <notifications@github.com>:

**Comment by ynswtf** [comment]
Yes I am having this problem now.

**Comment by virgil9306** [comment]
A specific date is not necessary but what will be the plan for this bug? It's a breaking bug for many.

**Comment by FraPazGal** [comment]
Hi @virgil9306,

We reproduced the issue so we shouldn't need any more info, but thank you for offering! 

Regarding an ETA, the related internal task have been assigned and the team would work on it in the following 1-2 weeks! At the moment we are still evaluating the possible solutions, so there is nothing fixed yet. We will update this issue as soon as there are any news.

**Comment by ANKUSH-JPG** [comment]
Yes , i am facing the same issue .
My opencart is running on :http://3.12.148.75:4111/
whenever i try to access http://3.12.148.75:4111/admin/  , the page successfully opens for me . After writing the username and password ,when i try to login it redirects me to: https://3.12.148.75:4111/admin/index.php?route=common/login

This is the error i receive in browser:

This site can’t provide a secure connection3.12.148.75 sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by juan131** [comment]
Hi everyone,

This is very likely to be related with the changes I recently introduced in the PR below:

- https://github.com/bitnami/bitnami-docker-opencart/pull/89

I will create a new PR that should fix this issue.
