### ISSUE TITLE
Sendmail not found

### ISSUE THREAD

**Issue by akashtalole** [bitnami/bitnami-docker-opencart#96]
sh: 1: /usr/sbin/sendmail: not found how to install it?

**Comment by beltran-rubo** [comment]
The container does not ship sendmail but the application is configurable to use a SMTP provider to send the emails through it.  Check how to configure a SMTP provider at https://github.com/bitnami/bitnami-docker-opencart#smtp-configuration

I hope it helps

**Comment by akashtalole** [comment]
Yes resolved using smtp settings. Thanks for quick reply.

**Comment by juan131** [comment]
Great @akashtalole ! I'm glad you could solve the issue providing the SMTP settings.
