### ISSUE TITLE
Uncaught ReferenceError: $ is not defined 

### ISSUE THREAD

**Issue by Eliah7** [bitnami/bitnami-docker-opencart#99]
**Description**

After running the container the following javascript error is seen.

<img width="1439" alt="Screenshot 2021-07-08 at 10 13 31" src="https://user-images.githubusercontent.com/23521788/124878811-2f541600-dfd5-11eb-89ab-ca73d34d1705.png">
<img width="976" alt="Screenshot 2021-07-08 at 10 13 20" src="https://user-images.githubusercontent.com/23521788/124878819-324f0680-dfd5-11eb-85d6-4923a10a02dc.png">

**Steps to reproduce the issue:**

```Dockerfile
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'docker.io/bitnami/opencart:3'
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=8080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
     depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
```

**Comment by juan131** [comment]
Hi @Eliah7 

Thanks for reporting this issue! It seems like an error in the application (Opencart) itself. I mean, it doesn't seem related with container, the Bitnami logic to configure Opencart nor the Apache configuration.

- Were you able to reproduce the same issue using different Opencart distributions?
- Are you able to reproduce the issue using different web browsers? Did you enable Javascript in your current browser?
